version: '3'
services:
  nest-app:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - postgres
    network_mode: "host"
    restart: always
    ports:
      - '3001:3001'
    env_file:
      - .env
    volumes:
      - flirtfever:/home/ubuntu/flirt-fever-backend

  postgres:
    image: postgres
    env_file:
      - .env
    environment:
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_USER=${DB_USERNAME}
      - POSTGRES_DB=${DB_NAME}
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  flirtfever:
  postgres_data: