version: '3'
services:
  nest-app:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - postgres
    restart: always
    ports:
      - '3001:3001'
    env_file:
      - .env
  postgres:
    image: postgres
    env_file:
      - .env
    environment:
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_USER=${DB_USERNAME}
      - POSTGRES_DB=${DB_NAME}
    ports:
      - '5432:5432'